FROM python:3.5-slim


WORKDIR /geoip
COPY requirements.txt requirements.txt
RUN pip install -U pip && \
        pip install -r requirements.txt
RUN mkdir data/        

COPY *.zip *.py geoname2fips.csv ./

ENTRYPOINT ["./geolite2legacy.py",  "-i", "GeoLite2-City-CSV_LIGHT.zip",  "-o", "/data/GeoLiteCity.dat",  "-f", "geoname2fips.csv"]